//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GYM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GYM()
        {
            this.ATHLETE = new HashSet<ATHLETE>();
        }
    
        public decimal ID { get; set; }
        public string NAME { get; set; }
        public string ADDRESS { get; set; }
        public string TEL { get; set; }
        public Nullable<decimal> BOSS_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATHLETE> ATHLETE { get; set; }
        public virtual ATHLETE BOSS { get; set; }
    }
}
