//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GyMasterDBEntities : DbContext
    {
        public GyMasterDBEntities()
            : base("name=GyMasterDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ATHLETE> ATHLETE { get; set; }
        public virtual DbSet<EXERCISE> EXERCISE { get; set; }
        public virtual DbSet<GYM> GYM { get; set; }
        public virtual DbSet<RESULT> RESULT { get; set; }
        public virtual DbSet<TRAINING_PLAN> TRAINING_PLAN { get; set; }
    }
}
