//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRAINING_PLAN
    {
        public decimal ATHLETE_ID { get; set; }
        public System.DateTime RELEASE_DATE { get; set; }
        public string FILENAME { get; set; }
    
        public virtual ATHLETE ATHLETE { get; set; }
    }
}
